config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :participants
  resources :secret_friend
  root 'participants#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  has_one :secret_friend_as_giver, class_name: 'SecretFriend', foreign_key: 'giver'
  has_one :secret_friend_as_receiver, class_name: 'SecretFriend', foreign_key: 'receiver'
end

app/models/secret_friend.rb
# frozen_string_literal: true

class SecretFriend < ApplicationRecord
  belongs_to :giver, class_name: 'Participant', foreign_key: 'giver'
  belongs_to :receiver, class_name: 'Participant', foreign_key: 'receiver'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController
  before_action :set_participant, only: %i[show edit update destroy]

  def index
    @participants = Participant.all
  end

  def new
    @participant = Participant.new
  end

  def create
    @participant = Participant.new(participant_params)

    if @participant.save
      redirect_to participants_path, notice: 'Participante adicionado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def show; end

  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_participant
    @participant = Participant.find(params[:id])
  end

  def participant_params
    params.require(:participant).permit(:name, :email)
  end
end

app/controllers/secret_friends_controller.rb
# frozen_string_literal: true

class SecretFriendsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/participants_helper.rb
# frozen_string_literal: true

module ParticipantsHelper
end

app/helpers/secret_friends_helper.rb
# frozen_string_literal: true

module SecretFriendsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmigoSecreto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_for @participant do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, 'error') %> prohibited this participant from being saved:</h2>

      <ul>
        <% @participant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editar Participante</h1>

<%= render 'form' %>

<%= link_to 'Voltar para a Lista', participants_path %>

app/views/participants/index.html.erb
<h1>Lista de Participantes</h1>

<% @participants.each do |participant| %>
  <p><%= participant.name %> - <%= participant.email %> <%= link_to 'Editar', edit_participant_path(participant) %> | <%= link_to 'Excluir', participant, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>

<% end %>

<p><%= link_to 'Adicionar Participante', new_participant_path %></p>

app/views/participants/new.html.erb
<h1>Adicionar Participante</h1>

<%= render 'form' %>

<%= link_to 'Voltar para a Lista', participants_path %>